---
- hosts: all
  become: ture
  tasks:
  
  - name: install apache2 package
    apt:
      name: apache2
      state: present
  
 - name: starting apache2 service
      service:
      name: apache2
      state: start