---
- hosts: all
  become: 
  pre_tasks:

  - name: install update on ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: copy default html file for site
    copy:
       src: default_site.html
       dest: /var/www/html/index.html 
       owner: root
       group: root
       mode: 0644

- hosts: web_server
  become: 
  tasks:

  - name: install apache2 and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: present
  
  - name: instal mariadb package
    apt:
        name: mariadb-server
        state: present
    when: ansible_distribution == "Ubuntu"

  - name: starting apache2 service
    service:
      name: apache2
      state: restarted

